In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from avparser.avlist import brands_code_list
## Display all the columns of the dataframe
pd.pandas.set_option('display.max_columns',None)

In [2]:
 df = pd.read_json('bmw.json')

In [3]:
df

,id,image,title,params,year,volume,engine,transmision,miles,link,price_ru,price_usd
0,1,https://avcdn.av.by/advertpreview/0000/2750/66...,"BMW 6 серия E63, E64","2005 г.автомат, 4.4 л, бензин185 000 км",2005,4.4,бензин,автомат,185000,/bmw/6-seriya/100348228,38006,14990
1,2,https://avcdn.av.by/advertpreview/0000/2609/41...,BMW 5 серия E39,"2002 г.автомат, 2.5 л, бензин297 000 км",2002,2.5,бензин,автомат,297000,/bmw/5-seriya/100342592,14071,5550
2,3,https://avcdn.av.by/advertpreview/0000/2736/61...,"BMW 5 серия F10, F11","2011 г.автомат, 3.0 л, дизель213 000 км",2011,3.0,дизель,автомат,213000,/bmw/5-seriya/100355390,40313,15900
3,4,https://avcdn.av.by/advertpreview/0000/2660/72...,"BMW 1 серия F20, F21","2017 г.механика, 1.5 л, дизель140 000 км",2017,1.5,дизель,механика,140000,/bmw/1-seriya/100332276,44370,17500
4,5,https://avcdn.av.by/advertpreview/0000/2737/22...,"BMW 5 серия F10, F11","2010 г.автомат, 3.0 л, бензин198 000 км",2010,3.0,бензин,автомат,198000,/bmw/5-seriya/100360918,32707,12900
...,...,...,...,...,...,...,...,...,...,...,...,...
2595,2596,https://avcdn.av.by/advertpreview/0000/2440/34...,"BMW X5 E70, 5 мест","2010 г.автомат, 4.4 л, бензин215 000 км",2010,4.4,бензин,автомат,215000,/bmw/x5/100315500,38792,15300
2596,2597,https://avcdn.av.by/advertpreview/0000/2595/26...,BMW 7 серия E38,"2001 г.автомат, 3.0 л, дизель404 000 км",2001,3.0,дизель,автомат,404000,/bmw/7-seriya/100340211,16962,6690
2597,2598,https://avcdn.av.by/advertpreview/0000/2387/99...,BMW 5 серия E34,"1995 г.механика, 2.5 л, бензин450 000 км",1995,2.5,бензин,механика,450000,/bmw/5-seriya/100223042,4564,0
2598,2599,https://avcdn.av.by/advertpreview/0000/0622/75...,"BMW 5 серия E60, E61","2007 г.автомат, 2.5 л, бензин245 000 км",2007,2.5,бензин,автомат,245000,/bmw/5-seriya/100033771,22058,8700
2599,2600,https://avcdn.av.by/advertpreview/0000/1474/42...,BMW 7 серия E65,"2006 г.автомат, 3.0 л, дизель320 000 км",2006,3.0,дизель,автомат,320000,/bmw/7-seriya/100170415,29664,11700

In [4]:
df.miles

0       185000
1       297000
2       213000
3       140000
4       198000
         ...
2595    215000
2596    404000
2597    450000
2598    245000
2599    320000
Name: miles, Length: 2600, dtype: int64

In [5]:
vol = df['miles'].unique()
vol

array([185000, 297000, 213000, 140000, 198000,  46000, 203000, 315000,
       145000, 179000, 555555, 162610, 336000, 170000, 400000, 280000,
       223400, 200000, 215000, 460000, 450000, 111111,      0, 175000,
       325000, 346165,  39000, 178000, 330000, 230000, 137650, 195000,
       158000, 316000, 123000,  84900,  21000, 500000, 441179, 167000,
       260000, 338200, 198826, 422000, 236000,  55555, 310000, 350000,
       390000, 247324, 420000, 100000, 246000, 300000, 176000, 250000,
       196000, 270000, 367000, 408000, 296000, 225000, 380000, 272000,
       314000, 340000, 224217, 107000, 218000, 535000,  91000, 458600,
         2450, 301800, 168100, 224573, 292000, 235000, 443000, 344500,
       268000, 430000, 291000, 150000, 142000, 360741, 340500, 137800,
       453000, 287000, 180000, 319000, 190000, 385000,  38500,  28000,
       291650, 999999, 394000,  49300, 357000, 356000, 202000, 167496,
       360000,  87000, 245000, 110000, 119000, 354055, 153000, 247000,
       360295, 382000, 276000, 134425,  23800, 570000, 209000, 125000,
       366000, 370000, 151000, 258000, 332000, 130000,  53000, 338000,
       149000, 157000, 220000, 324580, 600000,  96000, 320000, 370408,
       365000,  67000, 395000, 240000, 440000, 222000, 187000,  55000,
       262000, 411500, 375000, 377000, 279000, 327000, 228300, 273000,
        25400,   7700, 161000,  44000, 197235, 290200, 244465, 290000,
       277000, 290600, 283000, 311000, 257000, 139000, 483000, 317600,
        60800,  70000, 267522, 254322, 193000, 490000, 522000, 352000,
        90052, 296480, 700000,  62111, 135000, 183500, 444000, 133300,
        58000, 251000,  84226,  39800, 173683, 165045, 174000,  16000,
       345000, 106000, 156000, 402975, 323523, 284000, 480000, 302000,
       247500, 305000, 205000, 285000, 166000, 152000, 217000, 381000,
       485000, 510000, 186503, 147706, 165000, 216323, 583452, 347000,
       194000, 298000, 265000, 456000, 233333, 294000, 212000, 316200,
       267000,  71000, 181000, 406000, 244000, 313210, 543000, 504000,
       399400, 164000, 266900, 323400, 513000,  73000, 144000,  99999,
       504559, 186000, 210000, 126000, 341000, 405000,  14500, 282000,
        81000, 288900, 238000,  35000, 233000, 221500,  66000, 256666,
       256000, 137000, 463600,  89800, 357932, 349982, 145300, 171000,
       467000, 342995, 540000, 288000, 470000, 104000, 259147, 155000,
       380458, 428000, 112000, 176500, 223000, 451000, 399500, 309000,
        80000, 243323,  54000, 255000, 288500, 363000, 258800, 193350,
       476000, 120000,  88000, 222222, 386000, 214000, 286000, 201000,
       227000, 494000, 118000, 287540, 266000, 219000, 394200,  27000,
       108000,  64000, 141000, 182000, 177000,  82000, 160000, 333133,
       328000,  72000, 337000, 367500, 306000, 367029, 191000, 295000,
       146000, 334000, 313000, 119450, 233400, 445687, 358500, 293700,
        74500, 162000, 342000, 103000, 498134, 192000, 189000, 199000,
       127000, 268500, 417000, 188000, 160934, 134000, 168000, 317000,
       159276, 304000, 148000, 375500, 299000, 239000, 289000, 328719,
        64374, 333333, 150750,  45000, 159000, 228000, 247700, 258085,
       314191, 260823, 206000,  68000, 349000, 273500, 123456, 475352,
       435000, 250500, 224000, 250475, 229000, 343000,  50000, 290327,
       304554, 339000, 201300, 308500, 285650, 391000, 248214, 341600,
       355800, 388000, 275000,  25890, 320480, 235080, 295600, 234000,
       355600, 328911, 496018,  42000, 324789, 333000, 199998, 209500,
       355534, 652451, 226000, 445000, 143000,  38000, 415000, 216662,
       116000, 355000, 393000, 329000, 165500, 204000, 157350, 231000,
       184000,  47000,  16500, 335000, 518000, 293169, 350500, 169000,
       475000, 520000,  30500, 333956, 494700, 150100, 241000, 287500,
       311500, 329800,   5020, 337458, 172000, 254000, 138652, 343300,
       402000, 281000, 544375,  52000, 351871, 391635, 292900, 215618,
       360003, 174037, 453287, 360665, 340605, 232000,  23000, 369000,
       507505, 328088, 321000,  99000,  95000, 379000,  59000,  65000,
       349500,  51000, 426000, 211000, 444444, 322000, 352045, 131000,
       173000, 376000,  40600, 206777, 208000, 436000,  34000, 525000,
       387000, 318000, 129000, 509000, 253000, 362000, 614000, 291511,
        56000,  49350,  90000, 369852,  11111, 136650, 480300, 115000,
       181961,  18000, 211500, 392000, 400282, 235600, 371000, 361000,
       205854, 204122,  41000, 374000,  18969, 370653, 345767,  83000,
       278000, 259000, 166818, 445317, 273614, 261575, 259471, 301000,
       421000, 270193, 462685,  12200, 321123, 285836, 346400, 269000,
       358600, 369258, 344000, 386456, 416000,  30000, 300540, 322500,
       233500, 308000, 200356,  13726,  49190, 156380,  94447,  23970,
       168674,  77168,   2215,  16848,  13056,  10125,  56800,  12401,
        13903,  54194,  41806,  21376, 147000, 185879, 275437, 410000,
       240336, 278700,  86700, 413000, 278500, 173500, 149700,  51499,
       358645, 155100, 184352, 415300, 270500, 556700, 273277, 274000,
       397000,  52580,  86000, 293000, 186600, 220475, 221032, 488857,
       184400, 230811, 470306,  82600, 263500, 320100, 307000, 237776,
       372171,  95335, 138474, 274024, 154000, 193500,  90365, 132000,
       161200,  63000, 324523, 188395, 340938, 298937, 389000, 305622,
       350695, 193300, 447000, 111000, 105000, 183000,  38850, 442000,
       252000, 506000, 472000, 266700, 263000, 436300, 175700, 243000,
       351000, 321950, 411000, 362457, 323000, 436450, 374500, 315366,
       324000, 255220, 666666, 206500, 133860, 303000, 204400, 309900,
        83400, 197277, 502643, 300700, 285417, 221000, 175742, 414000,
       242000, 434522, 348212, 530000, 114000, 450125, 333265,  98000,
        61000, 136400, 187752, 489254, 407000, 336757,  76000,   5923,
       157956,  20899, 197000, 353000, 541000, 403000, 171805, 341852,
        83700, 162652, 132675, 180409, 183945, 423000, 411900,  93500,
        65656,  67400, 401000, 293590, 458000, 289359, 463000, 203400,
         6800, 113000,  27755, 328837, 271000, 550000, 193150, 372000,
       101000, 162700, 469000, 405430,   8065, 370853, 384242, 263822,
       270687, 134834, 346084, 130600, 275800, 266500,  81173, 267500,
       147850, 594000, 345543, 399000, 580000,  48000, 310052, 212300,
       397438, 419425, 376600, 284720, 207000, 283600, 245700,  75000,
       459000, 398500, 436147, 478000, 415863, 358909, 398000,  12000,
       264000, 163000, 141909, 215173, 326000,  17500, 148560, 331000,
        29000, 255500, 597000, 311896, 395122, 133000, 290800, 188084,
       380500, 380632, 167831, 159163, 356533, 438000, 249106,  96371,
       240500,  66115,  20600, 276520,  35632, 354700, 316700,  92500,
       296854, 351750, 102000, 120994, 446000, 390157, 179800, 325463,
       128000, 385407, 357002,  57700,  96100, 301240, 470050, 319250,
       155990, 195186,  93000, 257600,   3900, 348000, 443829, 234563,
       158500, 298323, 320054, 234180, 289215, 201601, 288303, 321612,
       616047, 368463, 384490, 449000, 298700, 452383, 264292, 315171,
        19000, 395646, 498756, 141500,  62000, 172997,   3000,  22000,
        52500, 139940, 199400,  31000,  36000, 346000, 109700, 354268,
       383000, 320789, 522314, 252300, 265200, 144585, 248000, 158800,
       294017, 283292,  85000, 336227, 325750, 216000, 197663,  41300,
        61800, 241560, 484000, 468442, 358963, 232145,   3500,  53800,
       299999, 517000, 547000, 163118, 384000, 247800, 368000, 312000,
       526730, 358000,  78000, 189900, 404000], dtype=int64)

In [8]:
for car_miles in vol:
    print(car_miles)
#     miles = df.query( 'miles == {}'.format(car_miles) ).miles.count()
#     print(miles)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1